name: CI/CD Pipeline para Flask App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Verificar versión de Docker y kubectl
        run: |
          docker --version
          kubectl version --client

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y subir la imagen de Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: donmiguel64/flask-devops-image2:latest

      - name: Configurar kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl config view
          kubectl get nodes

      - name: Desplegar en Kubernetes
        run: |
          kubectl apply -f k8s-deployment.yaml
          kubectl apply -f k8s-service.yaml
          kubectl get pods -o wide
