name: CI Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Hello world
        run: echo "El workflow se ejecutó correctamente 🚀"
