name: Test Docker Hub Login

on:
  workflow_dispatch: # permite lanzarlo manualmente desde GitHub

jobs:
  docker-login-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERTOKEN }}

      - name: Verificar login
        run: |
          echo "Login exitoso en Docker Hub"
